### PR TITLE
[SUN_OVERFLOW-2] Create form page for login

### PR DESCRIPTION
**Pull request by kenorenzsun**
## Backlog Link
https://framgiaph.backlog.com/view/SUN_OVERFLOW-2
## Commands
None
## Pre-conditions
None
## Expected Output
Login Form Markup
## Notes
None
## Screenshots
image

### CODE REVIEW

**Review by jules-lucero — APPROVED** [review]
Reviewed: 0.5
Comments: 0
Iteration: 0

**Review by nicoleamber — APPROVED** [review]
Reviewed: 0.5
Comments: 0
Iterations: 0

**Comment by ipilikent** [comment]
## Approved PR
-  The Sign in with Google button is displayed

## Proof
<details>

</details>

Test Case : 
-----
- Total Test time: 0.5 hrs.
- Total Comments: 0
- Total Iterations: 0

**Comment by ipilikent** [comment]
## Approved PR
-  the sign in with google button is displayed

## Proof
<details>

</details>

Test Case : 
-----
- Total Test time: 2 hrs
- Total Comments: 0
- Total Iterations: 0

**Comment by ipilikent** [comment]
## Approved PR
-  All displayed the same as the Figma design
- Sign in with Google button displayed
- Greetings message is displayed

## Proof
<details>

02 - Markup Log in

</details>

Test Case : https://docs.google.com/spreadsheets/d/114GrEn-LQQ8saIvjz9zqenuk05qmO4dN/edit#gid=1764252627
-----
- Total Test time: 0.5 hrs
- Total Comments: 0
- Total Iterations: 1

**Pull request merged**
