### PR TITLE
[Overflow-403] Refactor Admin Roles Page

### PR DESCRIPTION
**Pull request by nicoleamber**
## Backlog Link
https://framgiaph.backlog.com/view/SUN_OVERFLOW-403

## Commands
none

## Pre-conditions
* You must be an admin to access `/manage/roles`

## Expected Output

- [x] You should see the new design for Admin Roles page, as well as the modals within the page. 

## Screenshots
image
image
image
image

### CODE REVIEW

**Comment by jasonchuacodes** [comment]
image
Please double check in Figma: 

- font weight, font color, header background fill, 
- icons fill color, icon-family used
-  button stroke color

image
Please double check in Figma: 

 - padding
 - font-weight and size

**Review by kenorenzsun — DISMISSED** [review]

**Review by IanUrriza10 — APPROVED** [review]

**Review by IanUrriza10 — DISMISSED** [review]

**Review by IanUrriza10 — DISMISSED** [review]

**Review by kenorenzsun — DISMISSED** [review]

**Comment by nicoleamber** [comment]
Updated screenshots
image
image
image

**Comment by ipilikent** [comment]
# Roles Admin Page
Table - font color sa text
Modal input - label Name -> Role Name
Permission - set fixed container height & width
Text - align sa permissions - Center
Edit Role Button - Save
Buttons - height - 40px

**Comment by ipilikent** [comment]
# Comment

### Roles Admin Page

- Role Page Table 
      - font color of text should be Neutral/900
      - Name change to **ROLE**
- Modal input - Name Field change to **Role Name**
- Permission - set fixed container height & width
- Set Permissions Text - text-align: Center
- Edit Role Button - change to **Save Role button**
- Buttons - height: 40px

## Proof
<details>

image

image

image

</details>

**Comment by ipilikent** [comment]
## Approved PR
-  All displayed the same as the Figma design
- The new design for Admin Role Page
     - The modals
     - The table 
- Can add new role
- Can update role
- Can view role
- Can delete role
- Can cancel/close modal
- The modals are scrollable
- The hover and pagination is working
- All buttons are clickable and displayed

## Proof
<details>

403 - Refactor Roles Page (Admin)

</details>

Test Case: https://docs.google.com/spreadsheets/d/114GrEn-LQQ8saIvjz9zqenuk05qmO4dN/edit#gid=2001228601
-----
- Total Test time: 1 hr.
- Total Comments: 1
- Total Iterations: 1

**Review by ipilikent — DISMISSED** [review]

**Review by kenorenzsun — DISMISSED** [review]

**Review by IanUrriza10 — DISMISSED** [review]

**Review by jules-lucero — DISMISSED** [review]

**Review by kenorenzsun — APPROVED** [review]

**Review by IanUrriza10 — APPROVED** [review]

**Review by jules-lucero — APPROVED** [review]

**Pull request merged**
